# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  devco:
    image: jhgaleano6/devcopruebas:1.0.0
    restart: always
    ports:
      - 8000:8000